kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: regional-pd
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
parameters:
  type: pd-balanced
  replication-type: regional-pd
  availability-class: regional-hard-failover
volumeBindingMode: WaitForFirstConsumer